# First stage: install dependencies
FROM node:20.14 as build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Second stage: create a smaller final image
FROM node:20.14-alpine3.20

# Set the working directory
WORKDIR /app

# Copy the node_modules and application files from the build stage
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app .

# Specify the command to run the application
CMD ["npm", "run", "start"]
